"""
Lodestar — SQLAlchemy models.

Data model from DESIGN_AND_SCOPE.md §6:
  cases(id, name, status[active|paused|stopped], created_at, notes)
"""

from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from app.database import Base


class Case(Base):
    """A single OSINT investigation case.

    Status lifecycle:
        active  → paused  (can resume to active)
        active  → stopped (terminal — can only delete after this)
        paused  → active  (resume)
        paused  → stopped (terminal)

    Every other module checks case status before acting — pausing a case
    actually halts in-flight work, not just the UI display.
    """
    __tablename__ = "cases"

    id         = Column(Integer, primary_key=True, index=True)
    name       = Column(String(255), nullable=False)
    status     = Column(String(20), nullable=False, default="active")  # active | paused | stopped
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    notes      = Column(Text, nullable=True, default="")

    findings   = relationship("Finding", back_populates="case", cascade="all, delete-orphan")
    images     = relationship("Image", back_populates="case", cascade="all, delete-orphan")


class Finding(Base):
    """A single piece of OSINT evidence.
    
    Findings can be entered manually or generated by automated tools.
    Every finding MUST have a source URL per project hard scope.
    """
    __tablename__ = "findings"

    id         = Column(Integer, primary_key=True, index=True)
    case_id    = Column(Integer, ForeignKey("cases.id"), nullable=False, index=True)
    category   = Column(String(100), nullable=False)
    value      = Column(String(500), nullable=False)
    source_url = Column(Text, nullable=False)
    notes      = Column(Text, nullable=True, default="")
    verified   = Column(Boolean, nullable=False, default=True)
    added_at   = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))

    case       = relationship("Case", back_populates="findings")


class Image(Base):
    """An imported image with metadata."""
    __tablename__ = "images"

    id          = Column(Integer, primary_key=True, index=True)
    case_id     = Column(Integer, ForeignKey("cases.id"), nullable=False, index=True)
    path        = Column(String(500), nullable=False)
    source_url  = Column(Text, nullable=False)
    exif_json   = Column(Text, nullable=True, default="{}")
    imported_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))

    case        = relationship("Case", back_populates="images")
