"""
Lodestar — SQLAlchemy models.

Data model from DESIGN_AND_SCOPE.md §6:
  cases(id, name, status[active|paused|stopped], created_at, notes)
"""

from datetime import datetime, timezone
from typing import List, Optional
from sqlalchemy import String, Text, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import relationship, Mapped, mapped_column
from app.database import Base
from app.encryption import EncryptedString, EncryptedText


class Case(Base):
    """A single OSINT investigation case.

    Status lifecycle:
        active  → paused  (can resume to active)
        active  → stopped (terminal — can only delete after this)
        paused  → active  (resume)
        paused  → stopped (terminal)

    Every other module checks case status before acting — pausing a case
    actually halts in-flight work, not just the UI display.
    """
    __tablename__ = "cases"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")  # active | paused | stopped
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    notes: Mapped[Optional[str]] = mapped_column(EncryptedText, nullable=True, default="")

    findings: Mapped[List["Finding"]] = relationship(back_populates="case", cascade="all, delete-orphan")
    images: Mapped[List["Image"]] = relationship(back_populates="case", cascade="all, delete-orphan")
    relationships: Mapped[List["Relationship"]] = relationship(back_populates="case", cascade="all, delete-orphan")


class Finding(Base):
    """A single piece of OSINT evidence.
    
    Findings can be entered manually or generated by automated tools.
    Every finding MUST have a source URL per project hard scope.
    """
    __tablename__ = "findings"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    case_id: Mapped[int] = mapped_column(ForeignKey("cases.id"), nullable=False, index=True)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    value: Mapped[str] = mapped_column(EncryptedString(500), nullable=False)
    source_url: Mapped[str] = mapped_column(EncryptedText, nullable=False)
    notes: Mapped[Optional[str]] = mapped_column(EncryptedText, nullable=True, default="")
    verified: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    added_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))

    case: Mapped["Case"] = relationship(back_populates="findings")


class Image(Base):
    """An imported image with metadata."""
    __tablename__ = "images"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    case_id: Mapped[int] = mapped_column(ForeignKey("cases.id"), nullable=False, index=True)
    path: Mapped[str] = mapped_column(String(500), nullable=False)
    source_url: Mapped[str] = mapped_column(EncryptedText, nullable=False)
    exif_json: Mapped[Optional[str]] = mapped_column(EncryptedText, nullable=True, default="{}")
    imported_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))

    case: Mapped["Case"] = relationship(back_populates="images")


class Relationship(Base):
    """A discovered relationship between two entities."""
    __tablename__ = "relationships"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    case_id: Mapped[int] = mapped_column(ForeignKey("cases.id"), nullable=False, index=True)
    person_a: Mapped[str] = mapped_column(EncryptedString(255), nullable=False)
    relation: Mapped[str] = mapped_column(String(100), nullable=False)
    person_b: Mapped[str] = mapped_column(EncryptedString(255), nullable=False)
    source_url: Mapped[str] = mapped_column(EncryptedText, nullable=False)
    added_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))

    case: Mapped["Case"] = relationship(back_populates="relationships")
